title: Sasaki blog
description: "My personal blog where i share stuff i like"
author:
  name: "Sasaki"
  email: "[redacted]"
  url: "https://github.com/LeonardoSasaki/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Sasaki"
year : "2021"
